theme: jekyll-theme-minimal

title: ordered random forests
logo: https://raw.githubusercontent.com/fmuny/ORFpy/main/docs/images/orf-logo.png
description: random forest estimation of the ordered choice models
